/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
public class CustomerCheckin extends javax.swing.JFrame {

    Connection con=null;
   Statement st=null;
   PreparedStatement pst=null;
   ResultSet rs=null;
    public CustomerCheckin() {
     initComponents();
        SimpleDateFormat obj=new SimpleDateFormat("yyyy/MM/dd");
        Date date=new Date();
        txtdate.setText(obj.format(date));
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotels","root","kopal@1904");
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
       }
        Customer();
    }
    public void Customer(){
        try {
            pst=con.prepareStatement("Select roomnumber from room where bedtype=? and roomtype=? and status=?");
            pst.setString(1,jCombobedtype.getItemAt(jCombobedtype.getSelectedIndex()));
            pst.setString(2,jComboroomtype.getItemAt(jComboroomtype.getSelectedIndex()));
            pst.setString(3,"NOT-BOOKED");
            rs=pst.executeQuery();
            jComboroomnumber.removeAllItems();
            while(rs.next()){
               jComboroomnumber.addItem(rs.getString("roomnumber"));
            }
               pst=con.prepareStatement("select price from room where roomnumber=?");
               pst.setString(1,jComboroomnumber.getItemAt(jComboroomnumber.getSelectedIndex()));
               rs=pst.executeQuery();
               if(rs.next()){
                   txtprice.setText(rs.getString("price"));
               }
            
        } catch (SQLException ex) {
            Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmobileno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCombogender = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnatinonality = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtaadharnumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboroomtype = new javax.swing.JComboBox<>();
        jCombobedtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jComboroomnumber = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel1.setText("CUSTOMER CHECKIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 540, 70));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 420, -1));

        txtname.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 430, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MOBILE NO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 420, -1));

        txtmobileno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobilenoActionPerformed(evt);
            }
        });
        getContentPane().add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 440, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 440, 40));

        jCombogender.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCombogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jCombogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 405, 440, 30));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NATIONALITY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 430, -1));

        txtnatinonality.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtnatinonality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnatinonalityActionPerformed(evt);
            }
        });
        getContentPane().add(txtnatinonality, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 450, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AADHAR NUMBER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 430, -1));

        txtaadharnumber.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtaadharnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaadharnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtaadharnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 450, -1));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CHECK IN DATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 490, 40));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 490, -1));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ROOM TYPE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 490, -1));

        jComboroomtype.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jComboroomtype.setForeground(new java.awt.Color(51, 51, 51));
        jComboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC" }));
        jComboroomtype.setToolTipText("");
        jComboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboroomtypeItemStateChanged(evt);
            }
        });
        jComboroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 490, -1));

        jCombobedtype.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCombobedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        jCombobedtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombobedtypeItemStateChanged(evt);
            }
        });
        jCombobedtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombobedtypeActionPerformed(evt);
            }
        });
        getContentPane().add(jCombobedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 490, 30));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BED TYPE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 490, 50));

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ROOM NUMBER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 500, 40));

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRICE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 500, 40));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, 490, -1));

        btncheckin.setBackground(new java.awt.Color(255, 51, 51));
        btncheckin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btncheckin.setForeground(new java.awt.Color(0, 51, 51));
        btncheckin.setText("CHECK IN NOW");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });
        getContentPane().add(btncheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 750, 190, 40));

        btnclear.setBackground(new java.awt.Color(255, 51, 51));
        btnclear.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 750, 130, 40));

        jComboroomnumber.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jComboroomnumber.setForeground(new java.awt.Color(51, 51, 51));
        jComboroomnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item1", "Item2", "Item3", "Item4" }));
        getContentPane().add(jComboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 480, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\t.png")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobilenoActionPerformed

    private void txtnatinonalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnatinonalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnatinonalityActionPerformed

    private void txtaadharnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaadharnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaadharnumberActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void jCombobedtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombobedtypeActionPerformed
        Customer();
    }//GEN-LAST:event_jCombobedtypeActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
       if(txtname.getText().equals("")){
       txtname.requestFocus();
       JOptionPane.showMessageDialog(this, "All field is required");
    }
       else if(txtmobileno.getText().equals("")){
       txtmobileno.requestFocus();
       JOptionPane.showMessageDialog(this, "All field is required");
    }
       
       else if(txtnatinonality.getText().equals("")){
       txtnatinonality.requestFocus();
       JOptionPane.showMessageDialog(this, "All field is required");
    }
       else if(txtaadharnumber.getText().equals("")){
       txtaadharnumber.requestFocus();
       JOptionPane.showMessageDialog(this, "All field is required");
    }
       else{
           try {
               pst=con.prepareStatement("insert into customer(name,mobileno,gender,id,nationality,indate,roomnumber,roomtype,bedtype,price,status)values(?,?,?,?,?,?,?,?,?,?,?)");
                       pst.setString(1, txtname.getText());
                       pst.setString(2, txtmobileno.getText());
                       pst.setString(3, jCombogender.getItemAt(jCombogender.getSelectedIndex()));
                       pst.setString(4, txtaadharnumber.getText());
                       pst.setString(5, txtnatinonality.getText());
                       pst.setString(6, txtdate.getText());
                       pst.setString(7, jComboroomnumber.getItemAt(jComboroomnumber.getSelectedIndex()));
                       pst.setString(8, jComboroomtype.getItemAt(jComboroomtype.getSelectedIndex()));
                       pst.setString(9, jCombobedtype.getItemAt(jCombobedtype.getSelectedIndex()));
                       pst.setString(10, txtprice.getText());
                       pst.setString(11, "NULL");
                       pst.executeUpdate();
                       JOptionPane.showMessageDialog(this,"Customer Checked In Successfullyy ");
                       txtname.setText("");
        txtaadharnumber.setText("");
        txtmobileno.setText("");
        txtnatinonality.setText("");
        pst=con.prepareStatement("update room set status=? where roomnumber=?");
        pst.setString(1,"BOOKED");
        pst.setString(2,jComboroomnumber.getItemAt(jComboroomnumber.getSelectedIndex()));
        pst.executeUpdate();
        Customer();
           } catch (SQLException ex) {
               Logger.getLogger(CustomerCheckin.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_btncheckinActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtname.setText("");
        txtaadharnumber.setText("");
        txtmobileno.setText("");
        txtnatinonality.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboroomtypeActionPerformed
        Customer();
    }//GEN-LAST:event_jComboroomtypeActionPerformed

    private void jCombobedtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombobedtypeItemStateChanged
      //  Customer();
    }//GEN-LAST:event_jCombobedtypeItemStateChanged

    private void jComboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboroomtypeItemStateChanged
       // Customer();
    }//GEN-LAST:event_jComboroomtypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckin;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombobedtype;
    private javax.swing.JComboBox<String> jCombogender;
    private javax.swing.JComboBox<String> jComboroomnumber;
    private javax.swing.JComboBox<String> jComboroomtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtaadharnumber;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnatinonality;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
